name: test

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Env
        run: env
      - name: Docker Build
        run: docker build -t "${{secrets.DOCKER_REGISTRY}}/shug/demo:v1" .
      - name: Docker Login
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWD}} ${{DOCKER_REGISTRY}}
      - name: Docker Push
        run: docker push "${{DOCKER_REGISTRY}}/shug/demo:v1"

